[[colors.indexed_colors]]
color = "0x333333"
index = 248

[[colors.indexed_colors]]
color = "0xebe3ce"
index = 233

[[colors.indexed_colors]]
color = "0x949494"
index = 240

[[colors.indexed_colors]]
color = "0xebe3ce"
index = 236

[[colors.indexed_colors]]
color = "0xddffff"
index = 244

[[colors.indexed_colors]]
color = "0x000000"
index = 254

[[colors.indexed_colors]]
color = "0xdddddd"
index = 66

[colors.bright]
black = "0xbcbcbc"
blue = "0x6666bb"
cyan = "0x605faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0xaaaaaa"
text = "0xeeeeee"

[colors.normal]
black = "0xefe7d2"
blue = "0x0087af"
cyan = "0x005f87"
green = "0x00aa77"
# limegreen = "0x000000"
magenta = "0xdd00dd"
red = "0xee3333"
white = "0x444444"
yellow = "0x5f8700"

[colors.primary]
background = "0xefe7d2"
foreground = "0x333333"
