[colors.bright]
black = "0xbcbcbc"
blue = "0x6666bb"
cyan = "0x605faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0xaaaaaa"
text = "0xeeeeee"

[colors.normal]
black = "0xefe7d2"
blue = "0x0087af"
cyan = "0x005f87"
green = "0x00aa77"
magenta = "0xdd00dd"
red = "0xee3333"
white = "0x444444"
yellow = "0x5f8700"

[colors.primary]
background = "0xefe7d2"
foreground = "0x333333"
