[theme]
name = "solarized-dark"

[icons]
name = "awesome"

[icons.overrides]
backlight_empty = " _ "
backlight_partial1 = " ▂ "
backlight_partial2 = " ▄ "
backlight_partial3 = " ▆ "
backlight_full = " █ "

[theme.overrides]
idle_bg = "#000000"
idle_fg = "#93a1a1"
info_bg = "#000000"
info_fg = "#268bd2"

good_bg = "#002b42"
warning_bg = "#002b42"
critical_bg = "#002b42"

good_fg = "#93a1a1"
warning_fg = "#e7c547"
critical_fg = "#ff3334"

# separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlan0"
# format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
format = "{ssid} {signal_strength} {ip} {speed_up} {speed_down} "
interval = 5
use_bits = false

[[block]]
block = "backlight"

[[block]]
block = "custom"
command = ''' cat ~/.redshift.last '''
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "temperature"
collapsed = false
interval = 5
# format = "{min}° min, {max}° max, {average}° avg"
format = "{max}°C"
chip = "*-isa-*"
# inputs = ["CPUTIN", "SYSTIN"]

[[block]]
driver = "sysfs"
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %Y-%m-%d %H:%M:%S"


# [[block]]
# block = "networkmanager"
# on_click = "alacritty -e nmtui"
# interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
# interface_name_include = []
