name: panvimdoc

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - 'doc/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
    - uses: actions/checkout@v2
    - name: panvimdoc
      uses: kdheepak/panvimdoc@main
      with:
        vimdoc: fidget
        description: Standalone UI for nvim-lsp progress
        pandoc: doc/fidget.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto generate docs"
        branch: ${{ github.head_ref }}
